import React from "react";
import {
  IconLayoutGrid,
  IconHexagon,
  IconCirclePlus,
  IconDiamond,
  IconSquare,
  IconCircleDot,
  IconArrowLeft,
  IconList,
  IconTemplate,
  IconArrowDown,
  IconArrowUp,
  IconPlayerPlay,
  IconPlayerStop,
  IconPlayerTrackNext,
  IconClockPlay,
  IconCircleCheck,
  IconX,
  IconAlertTriangle,
  IconCircleCheckFilled,
  IconMinus,
  IconArrowRight,
  IconRotate,
  IconFolder,
  IconMinusVertical,
  IconDiamondFilled,
  IconSeparator,
  IconCode,
  IconBinaryTree2,
  IconTriangle,
  IconTriangleInverted,
  IconArrowsLeftRight,
  IconWaveSine,
  IconLayoutRows,
  IconFiles,
  IconFolderOpen,
  IconTerminal2,
  IconSettings,
  IconSearch,
  IconMapPin,
  IconGitBranch,
  IconHistory,
  IconBrandPython,
  IconFileCode,
} from "@tabler/icons-react";

const s = 18;
const st = 1.5;

export const ICONS: Record<string, React.ReactNode> = {
  DASHBOARD:   <IconLayoutGrid size={s} stroke={st} />,
  LINEAGE:     <IconHexagon size={s} stroke={st} />,
  CONNECTIONS: <IconCirclePlus size={s} stroke={st} />,
  PIPELINES:   <IconDiamond size={s} stroke={st} />,
  NODES:       <IconSquare size={s} stroke={st} />,
  ACTIVE:      <IconCircleDot size={s} stroke={st} />,
  ENV:         <IconCirclePlus size={s} stroke={st} />,
  BACK:        <IconArrowLeft size={s} stroke={st} />,
  LIST:        <IconList size={s} stroke={st} />,
  GRAPH:       <IconTemplate size={s} stroke={st} />,
  EXPORT:      <IconArrowDown size={s} stroke={st} />,
  IMPORT:      <IconArrowUp size={s} stroke={st} />,
  RUN:         <IconPlayerPlay size={s} stroke={st} />,
  STOP:        <IconPlayerStop size={s} stroke={st} />,
  RUNNING:     <IconPlayerTrackNext size={s} stroke={st} />,
  SCHEDULE:    <IconClockPlay size={s} stroke={st} />,
  SUCCESS:     <IconCircleCheck size={s} stroke={st} />,
  FAILED:      <IconX size={s} stroke={st} />,
  WARNING:     <IconAlertTriangle size={s} stroke={st} />,
  CLOSE:       <IconX size={s} stroke={st} />,
  CHECK:       <IconCircleCheckFilled size={s} stroke={st} />,
  DOT:         <IconMinus size={s} stroke={st} />,
  ARROW_RIGHT: <IconArrowRight size={s} stroke={st} />,
  UNDO:        <IconRotate size={s} stroke={st} />,
  REDO:        <IconRotate size={s} stroke={st} />,
  FOLDER:      <IconFolder size={s} stroke={st} />,
  EM_DASH:     <IconMinusVertical size={s} stroke={st} />,
  PARQUET:     <IconDiamondFilled size={s} stroke={st} />,
  CSV:         <IconSeparator size={s} stroke={st} />,
  JSON:        <IconCode size={s} stroke={st} />,
  DELTA:       <IconBinaryTree2 size={s} stroke={st} />,
  INPUT:       <IconTriangle size={s} stroke={st} />,
  OUTPUT:      <IconTriangleInverted size={s} stroke={st} />,
  DATASET:     <IconArrowsLeftRight size={s} stroke={st} />,
  STREAM:      <IconWaveSine size={s} stroke={st} />,
  STREAM_LOG:      <IconLayoutRows size={s} stroke={st} />,
  TEMPLATES:   <IconFiles size={s} stroke={st} />,
  BROWSE:      <IconFolderOpen size={s} stroke={st} />,
  LOGS:        <IconTerminal2 size={s} stroke={st} />,
  SETTINGS:    <IconSettings size={s} stroke={st} />,
  SEARCH:      <IconSearch size={s} stroke={st} />,
  PIN:         <IconMapPin size={s} stroke={st} />,
  GIT:         <IconGitBranch size={s} stroke={st} />,
  HISTORY:     <IconHistory size={s} stroke={st} />,
  PYTHON:      <IconBrandPython size={s} stroke={st} />,
  YAML:        <IconFileCode size={s} stroke={st} />,
};
