#!/usr/bin/env python3
"""Write the API's OpenAPI schema to a file.

`src/ducta/ui`'s `npm run spec:generate` has always invoked this path; the
script itself was never committed, so the UI's API client could only be
regenerated by someone who happened to have it lying around locally.

Usage:
    python scripts/dump_openapi.py [output.json]

    # from the UI package, which is how it is normally run:
    npm run spec:generate
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# Run from a source checkout without installing the package first.
_SRC = Path(__file__).resolve().parent.parent / "src"
if _SRC.is_dir() and str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))


def main(argv: list[str]) -> int:
    out = Path(argv[1]) if len(argv) > 1 else Path("openapi.json")

    try:
        from ducta.api.main import create_app
    except ImportError as exc:
        print(
            f"error: could not import the API ({exc}).\n"
            "The schema needs the optional 'api' extra: poetry install --extras api",
            file=sys.stderr,
        )
        return 1

    schema = create_app().openapi()

    out.parent.mkdir(parents=True, exist_ok=True)
    # sort_keys so regenerating without an API change produces no diff — the
    # point is to make a real schema change visible in review.
    out.write_text(json.dumps(schema, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    print(f"wrote {out} ({len(schema.get('paths', {}))} paths)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
